### ISSUE TITLE
Use only uuid as identifier of database records

### ISSUE THREAD

**Issue by baudoliver7** [my-supervisor/my-supervisor#58]
Currently, we use two types of identifier :

- integer (auto increment)
- uuid

Now, we want to use only uuid.

This task needs to redefine all classes and interfaces that interact with database and update the whole schema of database.

**Comment by 0pdd** [comment]
@baudoliver7 2 puzzles [#76](https://github.com/my-supervisor/my-supervisor/issues/76), [#77](https://github.com/my-supervisor/my-supervisor/issues/77) are still not solved.

**Comment by 0pdd** [comment]
@baudoliver7 the puzzle [#76](https://github.com/my-supervisor/my-supervisor/issues/76) is still not solved; solved: [#77](https://github.com/my-supervisor/my-supervisor/issues/77).
