### ISSUE TITLE
Use jooq as preferred way to access to database

### ISSUE THREAD

**Issue by baudoliver7** [my-supervisor/my-supervisor#59]
Currently, we use plain sql through `jdbc` to access to database. Now, we want to use `JOOQ`. We could use plain sql in some specific situation.

**Comment by 0pdd** [comment]
@baudoliver7 2 puzzles [#85](https://github.com/my-supervisor/my-supervisor/issues/85), [#86](https://github.com/my-supervisor/my-supervisor/issues/86) are still not solved.

**Comment by 0pdd** [comment]
@baudoliver7 the puzzle [#86](https://github.com/my-supervisor/my-supervisor/issues/86) is still not solved; solved: [#85](https://github.com/my-supervisor/my-supervisor/issues/85).
